name: Code Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # TODO: fix mypy for protobufs
  # mypy:
  #   runs-on: [ubuntu-22.04]
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install dependencies
  #     run: pip3 install -e .[dev]
  #   - name: Run mypy
  #     run: mypy

  pre-commit-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v3.0.1
        # this action also provides an additional behaviour when used in private repositories
        # when configured with a github token, the action will push back fixes to the pull request branch
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
